config/routes.rb
Rails.application.routes.draw do
  # get 'tasks/index'

  # get 'tasks/show'

  # get 'tasks/new'

  # post 'tasks/create'

  # post 'tasks/edit'

  # patch 'tasks/update'

  # delete 'tasks/delete'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to @task
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save

    redirect_to @task
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path

  end

  def task_params
    params.require(:task).permit(:name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f|%>
Name: <%= f.text_field :name%>
Content: <%= f.text_field :content%>
<%= f.submit%>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Overview Tasks</h1>

<ul>
<% @tasks.each_with_index do |task, index| %>
<li><%= index + 1 %> - <%=task.name %> <%= link_to 'Details', task_path(task) %> <%= link_to 'Edit', edit_task_path(task) %> <%= link_to 'Delete', task_path(task), method: :delete %>
</li>
<% end %>
</ul>

<%= link_to 'Create a new task', new_task_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>

<p><%= @task.content %></p>

Created at: <%= @task.created_at%>

<%= link_to "Back", tasks_path %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>